// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.
// You will need to replace these values with your own Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with your Firebase configuration
    // You can get this configuration from the Firebase Console
    // Project settings > General > Your apps > Add app
    return const FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-sender-id',
      projectId: 'your-project-id',
      authDomain: 'your-auth-domain',
      storageBucket: 'your-storage-bucket',
    );
  }
}
